@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyKlinix" as ReadOnlyKlinix
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class Klinix
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Klinix .up.|> ReadOnlyKlinix

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyKlinix
ModelManager -left-> "1" Klinix
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Klinix *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person

I -[hidden]up-> ModelManager

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

ModelManager --> "~* filtered" Person
@enduml
