@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedKlinix" as VersionedKlinix MODEL_COLOR
end box

[-> Model : undoKlinix()
activate Model

Model -> VersionedKlinix : undo()
activate VersionedKlinix

VersionedKlinix -> VersionedKlinix :resetData(ReadOnlyKlinix)
VersionedKlinix --> Model :
deactivate VersionedKlinix

[<-- Model
deactivate Model

@enduml
